### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by FGBxRamel** [German-Immersive-Railroading-Community/GIRBot#10]
![image](https://user-images.githubusercontent.com/30479611/145061057-b4a3f296-9f8a-40f4-a586-4ce175ea846f.png)

**Comment by Shirosaka** [comment]
Erster Fehler: Das ganze in Python zu schreiben. 🤡

**Comment by FGBxRamel** [comment]
[SO Article](https://stackoverflow.com/questions/1482141/what-does-it-mean-weakly-referenced-object-no-longer-exists) for that

**Comment by FGBxRamel** [comment]
They should be strong references trough being part of the DB-Class: ac7a4d4edd6a1912bfea64b77e17bb9feebc878c

**Comment by FGBxRamel** [comment]
Didn't fix; still the same error
