### ISSUE TITLE
New library

### ISSUE THREAD

**Issue by FGBxRamel** [German-Immersive-Railroading-Community/GIRBot#16]
Discord.py is unmaintained. Maybe there's a good and longtime maintained library.
***Status:*** [Replacing whole library with dc-py-interactions](https://github.com/German-Immersive-Railroading-Community/GIRBot/issues/16#issuecomment-1076107183)
Last Edit: Changed status (Replacing -> Replacing all)

- [x] Found functioning fork of d.py
- [x] Replace everything with discord-py-interactions
- [ ] Tested

**Comment by Shirosaka** [comment]
Following up with two forks of d.py:

- [pycord](https://docs.pycord.dev/en/master/)
- [nextcord](https://nextcord.readthedocs.io/en/latest/index.html)

As a side-note: the `discord-py-slash-command` package seems to be a major version behind, we could see if upgrading is a seamless process. (It seems it is now named `discord-py-interactions`).

This list might be edited in the future.

**Comment by FGBxRamel** [comment]
Update: nextcord seems easy to [integrate](https://nextcord.readthedocs.io/en/latest/migrating_to_nextcord.html).

**Comment by FGBxRamel** [comment]
Update: Nextcord will be the one which will be integrated

**Comment by FGBxRamel** [comment]
Update: Nextcord implemented [slash-command support](https://github.com/nextcord/nextcord/commit/65f8db96ec9392acf4634aa71182eb08bc3f9862) a 2 weeks ago. The discord-py-slash-commands will therefore be replaced.
**Example:** https://github.com/nextcord/nextcord/commit/95f64a8b5c520d4a8792c8bb0318900ee28af40d
Docs to that will be merged soon as mentioned [here](https://github.com/nextcord/nextcord/discussions/347#discussioncomment-1941366).

**Comment by FGBxRamel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replace current bot library](https://trello.com/c/XxYmbmHR/102-replace-current-bot-library)

**Comment by FGBxRamel** [comment]
Update: Replaced d.py with nexcort, waiting for https://github.com/nextcord/nextcord/pull/309 (Docs) to be merged

**Comment by FGBxRamel** [comment]
Update: Compiled the Docs myself, trying to work with that

**Comment by FGBxRamel** [comment]
Update: Docs merged, proceeding to replace dc-py-sc

**Comment by FGBxRamel** [comment]
Update: Need to wait for support of slash-command-permissions. See https://github.com/nextcord/nextcord/discussions/408#discussioncomment-2076769 for more a bit more information.

**Comment by FGBxRamel** [comment]
Update: Found more information.
Comments on an Issue in the GitHub of DC: https://github.com/discord/discord-api-docs/issues/2315#issuecomment-1003855439 | https://github.com/discord/discord-api-docs/issues/2315#issuecomment-1016391863 | https://github.com/discord/discord-api-docs/issues/2315#issuecomment-1016488307
[Some Notion](https://msciotti.notion.site/msciotti/Command-Permissions-V2-4d113cb49090409f998f3bd80a06c3bd) that was mentioned (can't verify tho)

**Comment by FGBxRamel** [comment]
Update: Since dc-py-interactions now is a standalone library, which is [mainly focused on slash-commands](https://discord-py-slash-command.readthedocs.io/en/latest/faq.html#where-should-we-go-with-discord-py-being-gone) and the other interactions, which we need, we'll use it.

**Comment by FGBxRamel** [comment]
Update: 3b92ddf40a2403ef2df2ecebc563abee388f7c80 replaces nextcord, testing now needed

**Comment by FGBxRamel** [comment]
Update: Why and what is that error?? Happens when applying for a role.
```
Task exception was never retrieved
future: <Task finished name='Task-20' coro=<application() done, defined at /home/girc/GIRBot/main.py:117> exception=MySQLInterfaceError('Python type Snowflake cannot be converted')>
Traceback (most recent call last):
  File "/home/girc/GIRBot/main.py", line 141, in application
    if db.count_app(ctx.author.id) > 2:
  File "/home/girc/GIRBot/db_handler.py", line 68, in count_app
    self.stat_execute(sql_str, adr)
  File "/home/girc/GIRBot/db_handler.py", line 35, in stat_execute
    self.cursor.execute(sql_str, adr)
  File "/home/girc/venvs/girbot/lib/python3.9/site-packages/mysql/connector/cursor_cext.py", line 257, in execute
    prepared = self._cnx.prepare_for_mysql(params)
  File "/home/girc/venvs/girbot/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 672, in prepare_for_mysql
    result = self._cmysql.convert_to_mysql(*params)
_mysql_connector.MySQLInterfaceError: Python type Snowflake cannot be converted
```

**Comment by MrTroble** [comment]
Was meint er mit Snowflake? User UID?
